name: swifty_proteins
description: "Swifty Protein is a cross-platform mobile application built with
  Flutter, designed for 3D visualization of ligands from the Protein Data Bank
  (PDB). The app allows users to search for specific ligands, interact with
  their 3D models, and explore their atomic structures using modern
  visualization tools."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^9.2.2
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  injectable: ^2.5.0
  local_auth: ^2.3.0
  native_screenshot_widget: ^0.0.8
  ngl_flutter:
    path: ../ngl_flutter
  overlay_support: ^2.1.0
  path_provider: ^2.1.5
  share_plus: ^10.1.3
  shared_preferences: ^2.3.4

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.3
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#89B0B2" # Цвет фона, если изображение не покроет экран полностью
  image: assets/icon_app/Assets.xcassets/AppIcon.appiconset/1024.png # Самое большое изображение
  android: true
  ios: true
  web: false
  android_gravity: fill # Растянуть изображение на весь экран
  ios_content_mode: scaleAspectFill # Растянуть изображение на весь экран
  fullscreen: true
